//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: authenticate.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `AuthenticateServiceClient`, then call methods of this protocol to make API calls.
internal protocol AuthenticateServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: AuthenticateServiceClientInterceptorFactoryProtocol? { get }

  func authenticate(
    _ request: AuthenticateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<AuthenticateRequest, AuthenticateResponse>
}

extension AuthenticateServiceClientProtocol {
  internal var serviceName: String {
    return "AuthenticateService"
  }

  /// Unary call to Authenticate
  ///
  /// - Parameters:
  ///   - request: Request to send to Authenticate.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func authenticate(
    _ request: AuthenticateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<AuthenticateRequest, AuthenticateResponse> {
    return self.makeUnaryCall(
      path: "/AuthenticateService/Authenticate",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAuthenticateInterceptors() ?? []
    )
  }
}

internal protocol AuthenticateServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'authenticate'.
  func makeAuthenticateInterceptors() -> [ClientInterceptor<AuthenticateRequest, AuthenticateResponse>]
}

internal final class AuthenticateServiceClient: AuthenticateServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: AuthenticateServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the AuthenticateService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: AuthenticateServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

