public typealias HelloworldAuthenticateRequest = AuthenticateRequest
public typealias HelloworldAuthenticateResponse = AuthenticateResponse
public typealias HelloworldAuthenticateServiceClient = AuthenticateServiceClient